version: '3.8'
services:
  banco_mysql:
    image: mysql:8.0
    container_name: TECH-PILL-DB
    environment:
      - MYSQL_DATABASE=klubi
      - MYSQL_USER=klubi_user
      - MYSQL_PASSWORD=klubi_pass
      - MYSQL_ROOT_PASSWORD=root_pass
    ports:
      - "3306:3306"